version: "3.7"

services:
    school_manager:
        build:
          args:
            user: admin
            uid: 1000
          context: ./
          dockerfile: Dockerfile
        image: school_manager_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
          - ./:/var/www
        networks:
          - school_manager_network

    nginx:
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - 8000:80
        - 443:443
      volumes:
        - ./:/var/www
        - ./nginx/:/etc/nginx/conf.d/
      networks:
        - school_manager_network
    school_db:
      image: mysql:5.7.22
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      volumes:
       - ./.docker/mysql/dbdata:/var/lib/mysql
      ports:
       - 3308:3306
      networks:
       - school_manager_network

networks:
  school_manager_network:
    driver: bridge    