name: ci-school-manager
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: shivammathur/setup-php@v2
       with:
         php-version: '8.1'
     - run: docker-compose up -d
     - run: docker-compose exec -it school_manager composer install
     - run: docker-compose exec -it school_manager php artisan key:generate
     - run: docker-compose exec -it school_manager php artisan test