name: ci-school-manager
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: shivammathur/setup-php@v2
     - uses: shogo82148/actions-setup-mysql@v1
       with:
         php-version: '8.1'
         mysql-version: '5.7'
     - run: mysql -uroot -h127.0.0.1 -e 'CREATE DATABASE school_manager_test' \
     'USE school_manager_test'    
     - run: composer install
     - run: php artisan key:generate
     - run: php artisan test